version: '3.3'

services:
  # 数据库模块
  xiaozhi-esp32-server-db:
    image: mysql:8.0
    container_name: xiaozhi-esp32-server-db
    restart: always
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=xiaozhi_esp32_server
      - MYSQL_INITDB_ARGS="--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  # Redis缓存模块
  xiaozhi-esp32-server-redis:
    image: redis:7-alpine
    container_name: xiaozhi-esp32-server-redis
    restart: always
    expose:
      - 6379
    environment:
      - TZ=Asia/Shanghai

  # 声纹识别模块 (3D-Speaker)
  xiaozhi-esp32-server-voiceprint:
    image: ghcr.io/xinnan-tech/voiceprint-api:latest
    container_name: xiaozhi-esp32-server-voiceprint
    restart: always
    depends_on:
      - xiaozhi-esp32-server-db
    ports:
      - "8005:8005"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./voiceprint/data:/app/data

  # manager-api和manager-web后台管理模块
  xiaozhi-esp32-server-web:
    image: ghcr.io/xinnan-tech/xiaozhi-esp32-server:web_latest
    container_name: xiaozhi-esp32-server-web
    restart: always
    depends_on:
      - xiaozhi-esp32-server-db
      - xiaozhi-esp32-server-redis
      - xiaozhi-esp32-server-voiceprint
    ports:
      - "8002:8002"
    environment:
      - TZ=Asia/Shanghai
      - SPRING_DATASOURCE_DRUID_URL=jdbc:mysql://xiaozhi-esp32-server-db:3306/xiaozhi_esp32_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&connectTimeout=30000&socketTimeout=30000&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      - SPRING_DATASOURCE_DRUID_USERNAME=root
      - SPRING_DATASOURCE_DRUID_PASSWORD=123456
      - SPRING_DATA_REDIS_HOST=xiaozhi-esp32-server-redis
      - SPRING_DATA_REDIS_PASSWORD=
      - SPRING_DATA_REDIS_PORT=6379
    volumes:
      - ./uploadfile:/uploadfile

  # Python 主服务端
  xiaozhi-esp32-server:
    image: ghcr.io/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xiaozhi-esp32-server
    restart: always
    depends_on:
      - xiaozhi-esp32-server-db
      - xiaozhi-esp32-server-redis
      - xiaozhi-esp32-server-web
      - xiaozhi-esp32-server-voiceprint
    ports:
      - "8000:8000"
      - "8003:8003"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/opt/xiaozhi-esp32-server/data
      - ./tmp:/opt/xiaozhi-esp32-server/tmp
      - ./models:/opt/xiaozhi-esp32-server/models
      - ./core:/opt/xiaozhi-esp32-server/core
      - ./music:/opt/xiaozhi-esp32-server/music
      - ./plugins_func:/opt/xiaozhi-esp32-server/plugins_func