version: '3.3'

services:
  xiaozhi-esp32-server:
    image: ghcr.io/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xiaozhi-esp32-server
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8003:8003"
    volumes:
      - ./data:/opt/xiaozhi-esp32-server/data
      - ./tmp:/opt/xiaozhi-esp32-server/tmp
      - ./models:/opt/xiaozhi-esp32-server/models
      - ./core:/opt/xiaozhi-esp32-server/core
    environment:
      - TZ=Asia/Shanghai